---
title: "CSIT165_Project2"
author: "Alex Yu and Audrey Lewis"
date: "12/19/2020"
output: html_document
urlcolor: blue
---

```{r Library, include=FALSE}
#for wget
library(HelpersMG)
#for reading in data
library(readr)
#install stringr
library(stringr)
#install dplyr
library(dplyr)
#install tidyr
library(tidyr)
#install magrittr
library(magrittr)
#install data table
library(data.table)
#install Kable
library(kableExtra)
#install for visualization
library(ggplot2)
#install for date function
library(lubridate)
#install tidyverse
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```


```{r Files, include=FALSE}

#Reading files for confirmedGlobal
# urlfile="./time_series_covid19_confirmed_global.csv"
# ConfirmedGlobal <- read_csv(url(urlfile))
ConfirmedGlobal <- read_csv("./time_series_covid19_confirmed_global.csv")

#Reading files for DeathsGlobal
#urlfile="./time_series_covid19_deaths_global.csv"
#DeathsGlobal <- read_csv(url(urlfile))
DeathsGlobal <- read_csv("./time_series_covid19_deaths_global.csv")

#Reading files for RecoveredGlobal
# urlfile="./time_series_covid19_recovered_global.csv"
# RecoveredGlobal <- read_csv(url(urlfile))
RecoveredGlobal <- read_csv("./time_series_covid19_recovered_global.csv")

#Reading files for confirmedGlobal
# urlfile="./time_series_covid19_confirmed_US.csv"
# ConfirmedUS <- read_csv(url(urlfile))
ConfirmedUS <- read_csv("./time_series_covid19_confirmed_US.csv")

#Reading files for DeathsGlobal
# urlfile="./time_series_covid19_deaths_US.csv"
# DeathsUS <- read_csv(url(urlfile))
DeathsUS <- read_csv("./time_series_covid19_deaths_US.csv")

```


<!-- testing section only -->
------

# Testing Section Only

```{r testUpload-1, echo=FALSE}
head(ConfirmedGlobal)
```

If the ConfirmedGlobal table was loaded correctly, you should see a tibble above with that data.

```{r testUpload-2, echo=FALSE}
head(DeathsGlobal)
```

If the DeathsGlobal table was loaded correctly, you should see a tibble above with that data.

```{r testUpload-3, echo=FALSE}
head(RecoveredGlobal)
```

If the RecoveredGlobal table was loaded correctly, you should see a tibble above with that data.

```{r testUpload-4, echo=FALSE}
head(ConfirmedUS)
```

If the ConfirmedUS table was loaded correctly, you should see a tibble above with that data.

```{r testUpload-5, echo=FALSE}
head(DeathsUS)
```

If the DeathsUS table was loaded correctly, you should see a tibble above with that data.

------
<!-- end testing section -->



# Objective 1 - Global Trajectory

<!-- assigned to Audrey -->
<!-- enter code here -->


# Objective 2 - Global Map

<!-- assigned to Audrey -->
<!-- enter code here -->


# Objective 3 - Narrowing Down Hot Spots

<!-- assigned to Audrey -->
<!-- enter code here -->


# Objective 4 - Zooming Into California

<!-- assigned to Alex -->
<!-- enter code here -->


# Objective 5 - Digging Deeper

<!-- assigned to Alex -->
<!-- enter code here -->




<!-- commenting this out until submission
     since it throws an error -->

<!-- ```{bash }
# commenting this out until submission
# since it throws an error
#
# git log --pretty=format:"%nSubject: %s%nAuthor: %aN%nDate: %aD%nBody: %b"

``` -->
